logging:
  level:
    root: debug

server:
  port: 9090

services:
  url:
    vets: http://localhost:8081/
    visits: http://localhost:8082/
    customers: http://localhost:8083/

spring:
  cloud:
    gateway:
      routes:
        - id: vets-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
