spring:
  application:
    name: customers-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    schema: classpath*:db/hsqldb/schema.sql
    data: classpath*:db/hsqldb/data.sql
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

