# Default values for spring-petclinic-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePull: Never

nameSpace: spring-pet-clinic
springActiveProfiles: kubernetes
configServerUrl: "http://spring-cloud-kubernetes-configserver:8888/"

apps:
  apiGateway:
    image: example.com/spring-petclinic/spring-petclinic-api-gateway
    tag: latest
    appName: api-gateway
    port: 8080
    targetPort: 8080
  customersService:
    image: example.com/spring-petclinic/spring-petclinic-customers-service
    tag: latest
    appName: customers-service
    port: 80
    targetPort: 8080
  visitsService:
    image: example.com/spring-petclinic/spring-petclinic-visits-service
    tag: latest
    appName: visits-service
    port: 80
    targetPort: 8080
  vetsService:
    image: example.com/spring-petclinic/spring-petclinic-vets-service
    tag: latest
    appName: vets-service
    port: 80
    targetPort: 8080
